name: Change Target Branch on PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - updated3
      - edited
      - reopened

jobs:
  change-target-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Change Target Branch
      run: |
        # Set the new target branch name
        echo $GITHUB_REF
        token=${{ secrets.TOKEN }}
        if git rev-parse --verify origin/release-candidate >/dev/null 2>&1; then
          echo "Branch Exsist"
        else
          exit 1
        fi  
        PR_DATA=$(curl -s -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}")

        TARGET_BRANCH=$(echo "$PR_DATA" | jq -r '.base.ref')
        echo "Target Branch: $TARGET_BRANCH"    

        if [[ "$TARGET_BRANCH" != "main" ]]
        then
          exit 0
          echo "Bhai Branch dekh le"
        fi  


        curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  -H "Authorization: Bearer $token" \
         https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/${{ github.event.pull_request.number }} -d '{"base": "${{ secrets.TARGET_BRANCH }}"}'
        
      env:
        TARGET_BRANCH: ${{ secrets.TARGET_BRANCH }}
